'use client';
import {useState} from 'react';
import type {ComponentType} from 'react';
import {LayoutDashboard,BookOpen,Users,CalendarDays,ClipboardCheck,Wallet,UserRound,BarChart3,Menu,Plus,Search,LogOut} from 'lucide-react';
const classes=[['Movers 1','Ms. Lan','P.01','T7-CN 09:00','12','Đang học'],['B1','Mr. Nam','P.02','T2-4-6 18:00','15','Đang học'],['Starters 2','Ms. Hoa','P.03','T3-5 17:30','10','Sắp mở'],['KET','Mr. Minh','P.04','T7-CN 14:00','8','Đang học']];
const students=[['HV001','Nguyễn Minh Anh','Movers 1','0901 234 567','Đã đóng'],['HV002','Trần Gia Huy','Movers 1','0902 345 678','Còn thiếu'],['HV003','Lê Hoàng Nam','B1','0903 456 789','Đã đóng'],['HV004','Phạm Lan Chi','Starters 2','0904 567 890','Chưa đóng']];
export default function Home(){const [tab,setTab]=useState('Dashboard');const [open,setOpen]=useState(false);const nav: Array<[string, ComponentType<any>]> = [['Dashboard',LayoutDashboard],['Lớp học',BookOpen],['Học viên',Users],['Lịch học',CalendarDays],['Điểm danh',ClipboardCheck],['Học phí',Wallet],['Giáo viên',UserRound],['Báo cáo',BarChart3]];return <div className="desktop-grid" style={{display:'grid',gridTemplateColumns:'250px 1fr',minHeight:'100vh'}}>
<aside className="sidebar" style={{padding:18}}><div style={{fontSize:20,fontWeight:800,marginBottom:28}}>🎓 Language Center</div>{nav.map(([n,I])=><div key={n} className={'navitem '+(tab===n?'active':'')} onClick={()=>setTab(n)}><I size={18}/>{n}</div>)}<div style={{marginTop:30,color:'#94a3b8',fontSize:12}}>OFFLINE CENTER • V1</div></aside>
<main><div className="mobilebar" style={{padding:14,background:'#111827',color:'#fff',alignItems:'center',gap:12}}><Menu/><b>Language Center</b></div><div className="content" style={{padding:28,maxWidth:1400,margin:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}><div><div style={{fontSize:13,color:'#667085'}}>QUẢN LÝ TRUNG TÂM</div><h1 style={{fontSize:28,margin:'5px 0'}}>{tab}</h1></div><button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={16} style={{verticalAlign:'middle'}}/> Thêm mới</button></div>
{tab==='Dashboard'&&<Dashboard/>}{tab==='Lớp học'&&<Table title="Danh sách lớp học" headers={['Lớp','Giáo viên','Phòng','Lịch học','Sĩ số','Trạng thái']} rows={classes}/>} {tab==='Học viên'&&<Table title="Danh sách học viên" headers={['Mã','Họ tên','Lớp','SĐT','Học phí']} rows={students}/>} {tab==='Lịch học'&&<Schedule/>}{tab==='Điểm danh'&&<Attendance/>}{tab==='Học phí'&&<Fees/>}{tab==='Giáo viên'&&<Teachers/>}{tab==='Báo cáo'&&<Reports/>}</div></main>{open&&<Modal close={()=>setOpen(false)}/>}</div>}
function Dashboard(){return <><div className="stats" style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16}}>{[['12','Lớp đang học'],['186','Học viên'],['8','Giáo viên'],['15','HS chưa đóng phí']].map(([v,l])=><div className="card" style={{padding:20}} key={l}><div style={{fontSize:30,fontWeight:800}}>{v}</div><div style={{color:'#667085',marginTop:5}}>{l}</div></div>)}</div><div style={{display:'grid',gridTemplateColumns:'1.5fr 1fr',gap:16,marginTop:16}}><div className="card" style={{padding:20}}><h3>Lịch học hôm nay</h3>{[['17:30','Starters 2','P.03','10 HS'],['18:00','B1','P.02','15 HS'],['19:30','Movers 1','P.01','12 HS']].map(x=><div key={x[1]} style={{display:'flex',justifyContent:'space-between',padding:'14px 0',borderBottom:'1px solid #eee'}}><b>{x[0]}</b><span>{x[1]} • {x[2]}</span><span className="pill blue">{x[3]}</span></div>)}</div><div className="card" style={{padding:20}}><h3>Tình trạng học phí</h3><div style={{fontSize:36,fontWeight:800}}>86%</div><div style={{color:'#667085'}}>đã hoàn tất trong tháng</div><div style={{marginTop:20,height:10,background:'#e5e7eb',borderRadius:10}}><div style={{width:'86%',height:10,background:'#2563eb',borderRadius:10}}/></div></div></div></>}
function Table({title,headers,rows}:{title:string,headers:string[],rows:string[][]}){return <div className="card" style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:15}}><h3>{title}</h3><div style={{display:'flex',gap:8}}><input className="input" style={{width:220}} placeholder="🔎 Tìm kiếm..."/><button className="btn btn-light">Xuất Excel</button></div></div><div className="table-wrap"><table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===r.length-1?<span className={'pill '+(c.includes('Đã')||c.includes('Đang')?'green':c.includes('thiếu')?'yellow':'red')}>{c}</span>:c}</td>)}</tr>)}</tbody></table></div></div>}
function Schedule(){return <div className="card" style={{padding:20}}><h3>Thời khóa biểu tuần</h3><div className="table-wrap"><table className="table"><thead><tr>{['Giờ','T2','T3','T4','T5','T6','T7','CN'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{['09:00','14:00','17:30','18:00','19:30'].map(t=><tr key={t}><td><b>{t}</b></td>{['T2','T3','T4','T5','T6','T7','CN'].map((d,i)=><td key={d}>{(t==='17:30'&&i===1)?'Starters 2':(t==='18:00'&&[0,2,4].includes(i))?'B1':(t==='09:00'&&i>=5)?'Movers 1':(t==='14:00'&&i>=5)?'KET':'—'}</td>)}</tr>)}</tbody></table></div></div>}
function Attendance(){return <div className="card" style={{padding:20}}><h3>Điểm danh hôm nay</h3><select className="input" style={{maxWidth:300,marginBottom:15}}><option>Movers 1</option><option>B1</option><option>Starters 2</option></select>{['Nguyễn Minh Anh','Trần Gia Huy','Phạm Lan Chi','Lê Hoàng Nam'].map((s,i)=><div key={s} style={{display:'flex',justifyContent:'space-between',padding:14,borderBottom:'1px solid #eee'}}><span>{s}</span><span><button className="btn btn-light">Có mặt</button> <button className="btn btn-light">Vắng</button></span></div>)}</div>}
function Fees(){return <div className="card" style={{padding:20}}><h3>Học phí tháng 10/2026</h3>{[['Đã đóng','160 HS','green'],['Đóng một phần','11 HS','yellow'],['Chưa đóng','15 HS','red']].map(x=><div key={x[0]} style={{display:'flex',justifyContent:'space-between',padding:16,borderBottom:'1px solid #eee'}}><span className={'pill '+x[2]}>{x[0]}</span><b>{x[1]}</b></div>)}</div>}
function Teachers(){return <Table title="Giáo viên" headers={['Họ tên','Lớp phụ trách','Số lớp','Lịch dạy','Trạng thái']} rows={[["Nguyễn Thị Lan","Movers 1; Flyers 1","2","T7-CN","Đang dạy"],["Trần Minh Nam","B1; KET","2","T2-4-6","Đang dạy"],["Lê Thị Hoa","Starters 2","1","T3-5","Đang dạy"]]}/>}
function Reports(){return <div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:16}}>{[['Doanh thu tháng','92.500.000đ'],['Tỷ lệ chuyên cần','94%'],['Học viên mới','18'],['Học viên nghỉ','3']].map(x=><div className="card" style={{padding:24}} key={x[0]}><div style={{color:'#667085'}}>{x[0]}</div><div style={{fontSize:30,fontWeight:800,marginTop:8}}>{x[1]}</div></div>)}</div>}
function Modal({close}:{close:()=>void}){return <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.45)',display:'grid',placeItems:'center',padding:20}}><div className="card" style={{padding:24,width:'min(520px,100%)'}}><div style={{display:'flex',justifyContent:'space-between'}}><h2>Thêm mới</h2><button className="btn btn-light" onClick={close}>✕</button></div><input className="input" placeholder="Họ tên / Tên lớp" style={{margin:'8px 0'}}/><input className="input" placeholder="Số điện thoại / Giáo viên" style={{margin:'8px 0'}}/><select className="input" style={{margin:'8px 0'}}><option>Chọn loại dữ liệu</option><option>Lớp học</option><option>Học viên</option><option>Giáo viên</option></select><button className="btn btn-primary" style={{width:'100%',marginTop:10}} onClick={close}>Lưu</button></div></div>}
