'use client';
import { useEffect, useMemo, useState } from 'react';
import type { ComponentType } from 'react';
import { LayoutDashboard, BookOpen, Users, CalendarDays, ClipboardCheck, Wallet, UserRound, BarChart3, Menu, Plus, Search, LogOut, Pencil, Trash2, X } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Teacher={id:string;full_name:string};
type Room={id:string;name:string;capacity:number};
type ClassRow={id:string;name:string;level:string|null;teacher_id:string|null;room_id:string|null;start_date:string|null;end_date:string|null;schedule_text:string|null;tuition:number;capacity:number;status:'active'|'upcoming'|'finished';teachers?:Teacher|null;rooms?:Room|null};

const nav: Array<[string, ComponentType<any>]> = [['Dashboard',LayoutDashboard],['Lớp học',BookOpen],['Học viên',Users],['Lịch học',CalendarDays],['Điểm danh',ClipboardCheck],['Học phí',Wallet],['Giáo viên',UserRound],['Báo cáo',BarChart3]];

export default function Home(){
  const [session,setSession]=useState<any>(null); const [loadingAuth,setLoadingAuth]=useState(true); const [tab,setTab]=useState('Dashboard'); const [mobile,setMobile]=useState(false);
  const client=supabase();
  useEffect(()=>{client.auth.getSession().then(({data})=>{setSession(data.session);setLoadingAuth(false)}); const {data:{subscription}}=client.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>subscription.unsubscribe()},[]);
  if(loadingAuth) return <div style={{minHeight:'100vh',display:'grid',placeItems:'center'}}>Đang tải...</div>;
  if(!session) return <Login/>;
  return <div className="desktop-grid" style={{display:'grid',gridTemplateColumns:'250px 1fr',minHeight:'100vh'}}>
    <aside className="sidebar" style={{padding:18}}><div style={{fontSize:20,fontWeight:800,marginBottom:28}}>🎓 Language Center</div>{nav.map(([n,I])=><div key={n} className={'navitem '+(tab===n?'active':'')} onClick={()=>{setTab(n);setMobile(false)}}><I size={18}/>{n}</div>)}<div style={{marginTop:30,color:'#94a3b8',fontSize:12}}>OFFLINE CENTER • V1</div><button className="btn btn-light" style={{marginTop:18,width:'100%'}} onClick={()=>client.auth.signOut()}><LogOut size={15}/> Đăng xuất</button></aside>
    <main><div className="mobilebar"><button className="btn btn-light" onClick={()=>setMobile(!mobile)}><Menu/></button><b>Language Center</b>{mobile&&<div className="mobilemenu">{nav.map(([n,I])=><div key={n} className={'navitem '+(tab===n?'active':'')} onClick={()=>{setTab(n);setMobile(false)}}><I size={18}/>{n}</div>)}<div className="navitem" onClick={()=>client.auth.signOut()}><LogOut size={18}/> Đăng xuất</div></div>}</div>
      <div className="content" style={{padding:28,maxWidth:1400,margin:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}><div><div style={{fontSize:13,color:'#667085'}}>QUẢN LÝ TRUNG TÂM</div><h1 style={{fontSize:28,margin:'5px 0'}}>{tab}</h1></div>{tab==='Lớp học'&&<button className="btn btn-primary" onClick={()=>window.dispatchEvent(new CustomEvent('open-class-modal'))}><Plus size={16}/> Thêm lớp</button>}</div>
        {tab==='Dashboard'&&<Dashboard/>}{tab==='Lớp học'&&<Classes/>}{tab==='Học viên'&&<Students/>}{tab==='Lịch học'&&<Schedule/>}{tab==='Điểm danh'&&<Attendance/>}{tab==='Học phí'&&<Fees/>}{tab==='Giáo viên'&&<Teachers/>}{tab==='Báo cáo'&&<Reports/>}
      </div></main>
  </div>
}

function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState(''); const client=supabase();
 return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20}}><div className="card" style={{width:'min(420px,100%)',padding:28}}><div style={{fontSize:28,fontWeight:800}}>🎓 Language Center</div><p style={{color:'#667085'}}>Đăng nhập quản lý trung tâm</p><input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><input className="input" style={{marginTop:10}} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu" type="password"/>{error&&<div style={{color:'#b42318',marginTop:10,fontSize:14}}>{error}</div>}<button className="btn btn-primary" style={{width:'100%',marginTop:14}} disabled={busy} onClick={async()=>{setBusy(true);setError('');const {error}=await client.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)}}>{busy?'Đang đăng nhập...':'Đăng nhập'}</button><p style={{fontSize:12,color:'#667085',marginTop:16}}>Tài khoản được tạo trong Supabase Authentication.</p></div></div>
}

function Dashboard(){const [stats,setStats]=useState({classes:0,students:0,teachers:0,unpaid:0});const client=supabase();useEffect(()=>{(async()=>{const [c,s,t,f]=await Promise.all([client.from('classes').select('id',{count:'exact',head:true}).eq('status','active'),client.from('students').select('id',{count:'exact',head:true}).eq('status','active'),client.from('teachers').select('id',{count:'exact',head:true}).eq('status','active'),client.from('fees').select('id',{count:'exact',head:true}).lt('amount_paid','amount_due')]);setStats({classes:c.count||0,students:s.count||0,teachers:t.count||0,unpaid:f.count||0})})()},[]);return <><div className="stats" style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16}}>{[[stats.classes,'Lớp đang học'],[stats.students,'Học viên'],[stats.teachers,'Giáo viên'],[stats.unpaid,'HS chưa đóng phí']].map(([v,l])=><div className="card" style={{padding:20}} key={String(l)}><div style={{fontSize:30,fontWeight:800}}>{v}</div><div style={{color:'#667085',marginTop:5}}>{l}</div></div>)}</div><div className="card" style={{padding:20,marginTop:16}}><h3>Dashboard dữ liệu thật</h3><p style={{color:'#667085'}}>Các chỉ số đang lấy trực tiếp từ Supabase. Các module tiếp theo sẽ dùng cùng dữ liệu này.</p></div></>}

function Classes(){const client=supabase();const [rows,setRows]=useState<ClassRow[]>([]);const [teachers,setTeachers]=useState<Teacher[]>([]);const [rooms,setRooms]=useState<Room[]>([]);const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState<ClassRow|null>(null);const [error,setError]=useState('');
 const load=async()=>{const [{data:c,error:ce},{data:t},{data:r}]=await Promise.all([client.from('classes').select('*,teachers(id,full_name),rooms(id,name,capacity)').order('created_at',{ascending:false}),client.from('teachers').select('id,full_name').eq('status','active').order('full_name'),client.from('rooms').select('id,name,capacity').order('name')]);if(ce)setError(ce.message);setRows((c||[]) as any);setTeachers(t||[]);setRooms(r||[])};
 useEffect(()=>{load();const h=()=>{setEditing(null);setOpen(true)};window.addEventListener('open-class-modal',h);return()=>window.removeEventListener('open-class-modal',h)},[]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.name} ${r.level||''} ${r.teachers?.full_name||''} ${r.rooms?.name||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const remove=async(id:string)=>{if(!confirm('Xóa lớp này?'))return;const {error}=await client.from('classes').delete().eq('id',id);if(error)setError(error.message);else load()};
 return <><div className="card" style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:15,gap:10,flexWrap:'wrap'}}><h3>Danh sách lớp học</h3><div style={{display:'flex',gap:8}}><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',left:10,top:11,color:'#98a2b3'}}/><input className="input" style={{width:260,paddingLeft:34}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm lớp, giáo viên..."/></div></div></div>{error&&<div style={{background:'#fef3f2',color:'#b42318',padding:10,borderRadius:8,marginBottom:10}}>{error}</div>}<div className="table-wrap"><table className="table"><thead><tr>{['Lớp','Trình độ','Giáo viên','Phòng','Lịch học','Sĩ số','Học phí','Trạng thái',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.level||'—'}</td><td>{r.teachers?.full_name||'—'}</td><td>{r.rooms?.name||'—'}</td><td>{r.schedule_text||'—'}</td><td>{r.capacity}</td><td>{Number(r.tuition||0).toLocaleString('vi-VN')}đ</td><td><span className={'pill '+(r.status==='active'?'green':r.status==='upcoming'?'yellow':'blue')}>{r.status==='active'?'Đang học':r.status==='upcoming'?'Sắp mở':'Đã kết thúc'}</span></td><td><div style={{display:'flex',gap:5}}><button className="btn btn-light" title="Sửa" onClick={()=>{setEditing(r);setOpen(true)}}><Pencil size={15}/></button><button className="btn btn-light" title="Xóa" onClick={()=>remove(r.id)}><Trash2 size={15}/></button></div></td></tr>)}{filtered.length===0&&<tr><td colSpan={9} style={{textAlign:'center',padding:30,color:'#667085'}}>Chưa có lớp học.</td></tr>}</tbody></table></div></div>{open&&<ClassModal row={editing} teachers={teachers} rooms={rooms} close={()=>setOpen(false)} saved={()=>{setOpen(false);load()}}/>}</>}

function ClassModal({row,teachers,rooms,close,saved}:{row:ClassRow|null;teachers:Teacher[];rooms:Room[];close:()=>void;saved:()=>void}){const client=supabase();const [form,setForm]=useState({name:row?.name||'',level:row?.level||'',teacher_id:row?.teacher_id||'',room_id:row?.room_id||'',schedule_text:row?.schedule_text||'',start_date:row?.start_date||'',end_date:row?.end_date||'',tuition:String(row?.tuition||''),capacity:String(row?.capacity||20),status:row?.status||'active'});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 const save=async()=>{if(!form.name.trim()){setError('Vui lòng nhập tên lớp.');return}setBusy(true);setError('');const payload={name:form.name.trim(),level:form.level||null,teacher_id:form.teacher_id||null,room_id:form.room_id||null,schedule_text:form.schedule_text||null,start_date:form.start_date||null,end_date:form.end_date||null,tuition:Number(form.tuition||0),capacity:Number(form.capacity||20),status:form.status};const res=row?await client.from('classes').update(payload).eq('id',row.id):await client.from('classes').insert(payload);if(res.error)setError(res.error.message);else saved();setBusy(false)};
 return <div className="modal-overlay"><div className="card modal"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>{row?'Sửa lớp học':'Thêm lớp học'}</h2><button className="btn btn-light" onClick={close}><X/></button></div><div className="form-grid"><label>Tên lớp<input className="input" value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Ví dụ: Movers 1"/></label><label>Trình độ<input className="input" value={form.level} onChange={e=>set('level',e.target.value)} placeholder="Starters / Movers / B1..."/></label><label>Giáo viên<select className="input" value={form.teacher_id} onChange={e=>set('teacher_id',e.target.value)}><option value="">Chưa chọn</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><label>Phòng<select className="input" value={form.room_id} onChange={e=>set('room_id',e.target.value)}><option value="">Chưa chọn</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name} ({r.capacity})</option>)}</select></label><label>Lịch học<input className="input" value={form.schedule_text} onChange={e=>set('schedule_text',e.target.value)} placeholder="T7-CN 09:00"/></label><label>Sĩ số tối đa<input className="input" type="number" min="1" value={form.capacity} onChange={e=>set('capacity',e.target.value)}/></label><label>Học phí/tháng<input className="input" type="number" min="0" value={form.tuition} onChange={e=>set('tuition',e.target.value)}/></label><label>Trạng thái<select className="input" value={form.status} onChange={e=>set('status',e.target.value)}><option value="active">Đang học</option><option value="upcoming">Sắp mở</option><option value="finished">Đã kết thúc</option></select></label></div>{error&&<div style={{color:'#b42318',marginTop:10}}>{error}</div>}<button className="btn btn-primary" style={{width:'100%',marginTop:16}} disabled={busy} onClick={save}>{busy?'Đang lưu...':'Lưu lớp học'}</button></div></div>}

function Students(){return <div className="card" style={{padding:20}}><h3>Học viên</h3><p style={{color:'#667085'}}>Module học viên sẽ kết nối trực tiếp với bảng students ở bước tiếp theo.</p></div>}
function Schedule(){return <div className="card" style={{padding:20}}><h3>Thời khóa biểu</h3><p style={{color:'#667085'}}>Lịch học sẽ lấy từ classes và schedules.</p></div>}
function Attendance(){return <div className="card" style={{padding:20}}><h3>Điểm danh</h3><p style={{color:'#667085'}}>Điểm danh sẽ lưu vào bảng attendance.</p></div>}
function Fees(){return <div className="card" style={{padding:20}}><h3>Học phí</h3><p style={{color:'#667085'}}>Học phí sẽ lưu vào bảng fees.</p></div>}
function Teachers(){const client=supabase();const [rows,setRows]=useState<Teacher[]>([]);useEffect(()=>{client.from('teachers').select('id,full_name').order('full_name').then(({data})=>setRows(data||[]))},[]);return <div className="card" style={{padding:20}}><h3>Giáo viên</h3>{rows.length?<ul>{rows.map(t=><li key={t.id}>{t.full_name}</li>)}</ul>:<p style={{color:'#667085'}}>Chưa có giáo viên.</p>}</div>}
function Reports(){return <div className="card" style={{padding:20}}><h3>Báo cáo</h3><p style={{color:'#667085'}}>Báo cáo sẽ lấy số liệu trực tiếp từ Supabase.</p></div>}
